threshold: 7
driver:
  path: drivers/geckodriver
  headless: True
no_ip:
  username: <login for no_ip account>
  password: <password for no_ip account>
sms.ru:
  api_id: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX
  phone_number: 7XXXXXXXXXX
